package engineshootout.GUI;

import city.cs.engine.SoundClip;
import engineshootout.Main.EngineShootout;
import java.io.IOException;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/**Class for GUI found on the on the top of the game
 * 
 * @author James Mori
 */

public class ControlGUI extends javax.swing.JPanel {

    private EngineShootout game;
    private boolean audioMuted;
    /**The name set by player 1
     */
    public String p1Name;
    /**The name set by player 2
     */
    public String p2Name;
    private static SoundClip buttonSelect, buttonError;
    
    static{
    try{
        buttonSelect = new SoundClip("data/audio/sfx/buttonSelect.wav");
        buttonError = new SoundClip("data/audio/sfx/buttonError.wav");
        }
        catch(UnsupportedAudioFileException|IOException|LineUnavailableException e){
            System.out.println(e);
        }
    }

    /**
     *
     * @param game the game
     */
    public ControlGUI(EngineShootout game) {
        this.game = game;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        audio = new javax.swing.JCheckBox();
        pause = new javax.swing.JCheckBox();
        quit = new javax.swing.JButton();
        p1NameField = new javax.swing.JLabel();
        p2NameField = new javax.swing.JLabel();

        setBackground(new java.awt.Color(56, 56, 56));
        setForeground(new java.awt.Color(56, 56, 56));

        audio.setBackground(new java.awt.Color(56, 56, 56));
        audio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/imagesGUI/audioOn.png"))); // NOI18N
        audio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audioActionPerformed(evt);
            }
        });

        pause.setBackground(new java.awt.Color(56, 56, 56));
        pause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/imagesGUI/pauseOn.png"))); // NOI18N
        pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });

        quit.setBackground(new java.awt.Color(56, 56, 56));
        quit.setForeground(new java.awt.Color(56, 56, 56));
        quit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/imagesGUI/exitOn.png"))); // NOI18N
        quit.setAutoscrolls(true);
        quit.setBorderPainted(false);
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });

        p1NameField.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        p1NameField.setForeground(new java.awt.Color(255, 255, 255));

        p2NameField.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        p2NameField.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(p1NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 513, Short.MAX_VALUE)
                .addComponent(pause)
                .addGap(18, 18, 18)
                .addComponent(audio)
                .addGap(18, 18, 18)
                .addComponent(quit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(707, Short.MAX_VALUE)
                    .addComponent(p2NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(213, 213, 213)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(quit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(audio, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(p1NameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(pause, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(p2NameField, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void audioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audioActionPerformed
        buttonSelect.play();
        if (audio.isSelected() && game.getStageNo() !=6) {
            System.out.println("audio paused");
            audio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/imagesGUI/audioOff.png")));
            game.world.stageMusic.stop();
            audioMuted = true;
            if (game.getStageNo() != 0) {
            game.getView().requestFocus();
            }
        }
        else if (!audio.isSelected() && game.getStageNo() != 6) {
            System.out.println("audio playing");
            audio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/imagesGUI/audioOn.png")));
            game.world.stageMusic.play();
            game.world.stageMusic.loop();
            audioMuted = false;
            if (game.getStageNo() != 0) {
            game.getView().requestFocus();
            }
        }
    }//GEN-LAST:event_audioActionPerformed

    private void pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseActionPerformed
        if (game.getStageNo() == 0) {
            buttonError.setVolume(0.3);
            buttonError.play();
        }
        else {
            buttonSelect.play();
            if (pause.isSelected() && game.getStageNo() != 6) {
                System.out.println("paused");
                pause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/imagesGUI/pauseOff.png")));
                if (audioMuted == false) {
                game.world.stageMusic.pause();
                }
                game.world.stop();
                game.getView().requestFocus();
            }
            else if (!pause.isSelected() && game.getStageNo() != 6) {
                System.out.println("played");
                pause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/imagesGUI/pauseOn.png")));
                if (audioMuted == false) {
                game.world.stageMusic.resume();
                game.world.stageMusic.loop();
                }
                game.world.start();
                game.getView().requestFocus();
            }
        }
    }//GEN-LAST:event_pauseActionPerformed

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        buttonSelect.play();
        quit.setRolloverEnabled(false);
        //quit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/exitOff.png")));
        System.out.println("Closing game...");
        System.exit(0);
    }//GEN-LAST:event_quitActionPerformed

    /**Displays the name set by player 1
     *
     * @param p1Text the name set by player 1
     */
    public void setP1NameField(String p1Text) {
        p1NameField.setText(p1Text);
    }

    /**Displays the name set by player 2
     *
     * @param p2Text the name set by player 2
     */
    public void setP2NameField(String p2Text) {
        p2NameField.setText(p2Text);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox audio;
    private javax.swing.JLabel p1NameField;
    private javax.swing.JLabel p2NameField;
    private javax.swing.JCheckBox pause;
    private javax.swing.JButton quit;
    // End of variables declaration//GEN-END:variables
  
}
