package engineshootout.GUI;

import city.cs.engine.SoundClip;
import city.cs.engine.UserView;
import engineshootout.Main.EngineShootout;
import java.io.IOException;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/**This is the main menu of the game. It allows the user to enter their name and
 * choose their car colour before playing the game - note that while the players
 * must choose a colour, if they leave the name field blank it will automatically
 * set their name to either Player 1 or Player 2. 
 * There are also buttons to view the credits of the game and to quit.
 * 
 * @author James Mori
 */

public class MainMenu extends javax.swing.JPanel {
    private EngineShootout game;
    private UserView view;
    private ControlGUI gui;
    private static SoundClip buttonSelect, buttonConfirm, buttonError;
    private boolean p1SelectedColour = false;
    private boolean p2SelectedColour = false;
    private boolean p1SelectedName = false;
    private boolean p2SelectedName = false;

    /**This is the string that contains the colour of the car player 1 chooses
     *
     */
    public String leftCarSelection;

    /**This is the string that contains the colour of the car player 2 chooses
     *
     */
    public String rightCarSelection;
    
    static{
    try{
        buttonSelect = new SoundClip("data/audio/sfx/buttonSelect.wav");
        buttonConfirm = new SoundClip("data/audio/sfx/buttonConfirm.wav");
        buttonError = new SoundClip("data/audio/sfx/buttonError.wav");
        }
        catch(UnsupportedAudioFileException|IOException|LineUnavailableException e){
            System.out.println(e);
        }
    }

    /**
     *
     * @param game
     * @param view
     * @param gui
     */
    public MainMenu(EngineShootout game, UserView view, ControlGUI gui) {
        this.game = game;
        this.view = view;
        this.gui = gui;
        
        initComponents();
        
        p1EditButton.setVisible(false);
        p2EditButton.setVisible(false);
    }

    /**
     * @return Player 1's selected colour
     */
    public String getLeftCarSelection() {
        return leftCarSelection;
    }
    /**
     * 
     * @return Player 2's selected colour
     */
    public String getRightCarSelection() {
        return rightCarSelection;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creditsDialogMenu = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        creditsAudio = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        creditsImages = new javax.swing.JTextArea();
        closeCredits = new javax.swing.JButton();
        instructionsDialogMenu = new javax.swing.JDialog();
        instructionsImage = new javax.swing.JLabel();
        blueCarLeftIcon = new javax.swing.JLabel();
        greenCarLeftIcon = new javax.swing.JLabel();
        purpleCarLeftIcon = new javax.swing.JLabel();
        redCarLeftIcon = new javax.swing.JLabel();
        yellowCarLeftIcon = new javax.swing.JLabel();
        greenCarRightIcon = new javax.swing.JLabel();
        purpleCarRightIcon = new javax.swing.JLabel();
        redCarRightIcon = new javax.swing.JLabel();
        yellowCarRightIcon = new javax.swing.JLabel();
        blueCarRightIcon = new javax.swing.JLabel();
        selectedRightCar = new javax.swing.JLabel();
        selectedLeftCar = new javax.swing.JLabel();
        playButton = new javax.swing.JButton();
        p2TextField = new javax.swing.JTextField();
        p1TextField = new javax.swing.JTextField();
        p1OkButton = new javax.swing.JButton();
        p2OkButton = new javax.swing.JButton();
        p2NameField = new javax.swing.JLabel();
        p1NameField = new javax.swing.JLabel();
        p2EditButton = new javax.swing.JButton();
        p1EditButton = new javax.swing.JButton();
        creditsButton = new javax.swing.JButton();
        gameNameField = new javax.swing.JLabel();
        quitButton = new javax.swing.JButton();
        instructionsButton = new javax.swing.JButton();

        creditsDialogMenu.setTitle("Credits - Engine Shootout");
        creditsDialogMenu.setAlwaysOnTop(true);
        creditsDialogMenu.setBackground(new java.awt.Color(56, 56, 56));
        creditsDialogMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Created by James Mori");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Audio Credits:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Image Credits:");

        creditsAudio.setColumns(20);
        creditsAudio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        creditsAudio.setRows(5);
        creditsAudio.setText(" \t  MUSIC:\n  Menu:      \t          joshuaempyre\n  Stage 1:   \t          Manuel F. Graf\n  Stage 2: \t          lena_orsa\n  Stage 3:   \t          frankum\n  Stage 4:\t          burning-mir\n  Stage 5:\t          Sunsai\n\n\n\t     SFX:\n  Crowd noise:            tim.kahn\n  Ball kicks:\t         CGEffex\n  Goal cheering:         paulw2k\n  Bang noise:              Eelke\n  Engine noise:           InspectorJ\n  Button press:           fins\n  Button confirm:       InspectorJ\n  Button error:            mad-monkey\n  Stage progress:      Marregheriti");
        jScrollPane1.setViewportView(creditsAudio);

        creditsImages.setColumns(20);
        creditsImages.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        creditsImages.setRows(2);
        creditsImages.setText("Game art assets obtained from:\nwww.gameart2d.com/freebies.html");
        jScrollPane2.setViewportView(creditsImages);

        closeCredits.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/ImagesGUI/exitOn.png"))); // NOI18N
        closeCredits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeCreditsMouseClicked(evt);
            }
        });
        closeCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeCreditsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout creditsDialogMenuLayout = new javax.swing.GroupLayout(creditsDialogMenu.getContentPane());
        creditsDialogMenu.getContentPane().setLayout(creditsDialogMenuLayout);
        creditsDialogMenuLayout.setHorizontalGroup(
            creditsDialogMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditsDialogMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(creditsDialogMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(creditsDialogMenuLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        creditsDialogMenuLayout.setVerticalGroup(
            creditsDialogMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditsDialogMenuLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(creditsDialogMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(closeCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        instructionsImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/ImagesGUI/instructionsMenu.png"))); // NOI18N

        javax.swing.GroupLayout instructionsDialogMenuLayout = new javax.swing.GroupLayout(instructionsDialogMenu.getContentPane());
        instructionsDialogMenu.getContentPane().setLayout(instructionsDialogMenuLayout);
        instructionsDialogMenuLayout.setHorizontalGroup(
            instructionsDialogMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(instructionsImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        instructionsDialogMenuLayout.setVerticalGroup(
            instructionsDialogMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(instructionsImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(56, 56, 56));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        blueCarLeftIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/ImagesGUI/blueCarLeft.png"))); // NOI18N
        blueCarLeftIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blueCarLeftIconMouseClicked(evt);
            }
        });

        greenCarLeftIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/ImagesGUI/greenCarLeft.png"))); // NOI18N
        greenCarLeftIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                greenCarLeftIconMouseClicked(evt);
            }
        });

        purpleCarLeftIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/ImagesGUI/purpleCarLeft.png"))); // NOI18N
        purpleCarLeftIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purpleCarLeftIconMouseClicked(evt);
            }
        });

        redCarLeftIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/ImagesGUI/redCarLeft.png"))); // NOI18N
        redCarLeftIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redCarLeftIconMouseClicked(evt);
            }
        });

        yellowCarLeftIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/ImagesGUI/yellowCarLeft.png"))); // NOI18N
        yellowCarLeftIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yellowCarLeftIconMouseClicked(evt);
            }
        });

        greenCarRightIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/ImagesGUI/greenCarRight.png"))); // NOI18N
        greenCarRightIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                greenCarRightIconMouseClicked(evt);
            }
        });

        purpleCarRightIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/ImagesGUI/purpleCarRight.png"))); // NOI18N
        purpleCarRightIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purpleCarRightIconMouseClicked(evt);
            }
        });

        redCarRightIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/ImagesGUI/redCarRight.png"))); // NOI18N
        redCarRightIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redCarRightIconMouseClicked(evt);
            }
        });

        yellowCarRightIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/ImagesGUI/yellowCarRight.png"))); // NOI18N
        yellowCarRightIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yellowCarRightIconMouseClicked(evt);
            }
        });

        blueCarRightIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/ImagesGUI/blueCarRight.png"))); // NOI18N
        blueCarRightIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blueCarRightIconMouseClicked(evt);
            }
        });

        selectedRightCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/ImagesGUI/testDefaultR.png"))); // NOI18N

        selectedLeftCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/ImagesGUI/testDefaultL.png"))); // NOI18N

        playButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        playButton.setText("Play!");
        playButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playButtonMouseClicked(evt);
            }
        });

        p2TextField.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        p2TextField.setForeground(new java.awt.Color(100, 100, 100));
        p2TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p2TextField.setText("enter your name here");
        p2TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p2TextFieldMouseClicked(evt);
            }
        });
        p2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2TextFieldActionPerformed(evt);
            }
        });

        p1TextField.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        p1TextField.setForeground(new java.awt.Color(100, 100, 100));
        p1TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p1TextField.setText("enter your name here");
        p1TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p1TextFieldMouseClicked(evt);
            }
        });
        p1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1TextFieldActionPerformed(evt);
            }
        });

        p1OkButton.setText("OK");
        p1OkButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p1OkButtonMouseClicked(evt);
            }
        });
        p1OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1OkButtonActionPerformed(evt);
            }
        });

        p2OkButton.setText("OK");
        p2OkButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p2OkButtonMouseClicked(evt);
            }
        });

        p2NameField.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        p2NameField.setForeground(new java.awt.Color(255, 255, 255));

        p1NameField.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        p1NameField.setForeground(new java.awt.Color(255, 255, 255));

        p2EditButton.setText("Edit");
        p2EditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p2EditButtonMouseClicked(evt);
            }
        });

        p1EditButton.setText("Edit");
        p1EditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p1EditButtonMouseClicked(evt);
            }
        });

        creditsButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        creditsButton.setText("Credits");
        creditsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditsButtonMouseClicked(evt);
            }
        });
        creditsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsButtonActionPerformed(evt);
            }
        });

        gameNameField.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        gameNameField.setForeground(new java.awt.Color(255, 255, 255));
        gameNameField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameNameField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/ImagesGUI/bannerMenu.png"))); // NOI18N

        quitButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        quitButton.setText("Quit");
        quitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitButtonMouseClicked(evt);
            }
        });
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        instructionsButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        instructionsButton.setText("Instructions");
        instructionsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                instructionsButtonMouseClicked(evt);
            }
        });
        instructionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructionsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(p1EditButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(p1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(p1OkButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(p2EditButton)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(p1NameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(198, 198, 198)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(p2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(p2OkButton))
                    .addComponent(p2NameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gameNameField)
                .addGap(250, 250, 250))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(selectedLeftCar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(blueCarLeftIcon)
                        .addGap(35, 35, 35)
                        .addComponent(greenCarLeftIcon)
                        .addGap(35, 35, 35)
                        .addComponent(purpleCarLeftIcon)
                        .addGap(35, 35, 35)
                        .addComponent(redCarLeftIcon)
                        .addGap(35, 35, 35)
                        .addComponent(yellowCarLeftIcon)))
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(creditsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(157, 157, 157)
                        .addComponent(blueCarRightIcon)
                        .addGap(35, 35, 35)
                        .addComponent(greenCarRightIcon)
                        .addGap(35, 35, 35)
                        .addComponent(purpleCarRightIcon)
                        .addGap(35, 35, 35)
                        .addComponent(redCarRightIcon)
                        .addGap(35, 35, 35)
                        .addComponent(yellowCarRightIcon)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(instructionsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(playButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(192, 192, 192)
                        .addComponent(selectedRightCar)
                        .addGap(70, 70, 70))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameNameField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p2NameField, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(p1NameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p1OkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2OkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p1EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectedRightCar)
                            .addComponent(selectedLeftCar))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yellowCarRightIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blueCarRightIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(greenCarRightIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(purpleCarRightIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(redCarRightIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yellowCarLeftIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blueCarLeftIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(greenCarLeftIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(purpleCarLeftIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(redCarLeftIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(instructionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(creditsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void blueCarLeftIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blueCarLeftIconMouseClicked
        buttonSelect.play();
        selectedLeftCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/ImagesGUI/bigSize/blueCarLeft.png")));
        leftCarSelection = "blue";
        p1SelectedColour = true;
    }//GEN-LAST:event_blueCarLeftIconMouseClicked

    private void greenCarLeftIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_greenCarLeftIconMouseClicked
        buttonSelect.play();
        selectedLeftCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/ImagesGUI/bigSize/greenCarLeft.png")));
        leftCarSelection = "green";
        p1SelectedColour = true;
    }//GEN-LAST:event_greenCarLeftIconMouseClicked

    private void purpleCarLeftIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purpleCarLeftIconMouseClicked
        buttonSelect.play();
        selectedLeftCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/ImagesGUI/bigSize/purpleCarLeft.png")));
        leftCarSelection = "purple";
        p1SelectedColour = true;
    }//GEN-LAST:event_purpleCarLeftIconMouseClicked

    private void redCarLeftIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redCarLeftIconMouseClicked
        buttonSelect.play();
        selectedLeftCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/ImagesGUI/bigSize/redCarLeft.png")));
        leftCarSelection = "red";
        p1SelectedColour = true;
    }//GEN-LAST:event_redCarLeftIconMouseClicked

    private void yellowCarLeftIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yellowCarLeftIconMouseClicked
        buttonSelect.play();
        selectedLeftCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/ImagesGUI/bigSize/yellowCarLeft.png")));
        leftCarSelection = "yellow";
        p1SelectedColour = true;
    }//GEN-LAST:event_yellowCarLeftIconMouseClicked

    private void blueCarRightIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blueCarRightIconMouseClicked
        buttonSelect.play();
        selectedRightCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/ImagesGUI/bigSize/blueCarRight.png")));
        rightCarSelection = "blue";
        p2SelectedColour = true;
    }//GEN-LAST:event_blueCarRightIconMouseClicked

    private void greenCarRightIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_greenCarRightIconMouseClicked
        buttonSelect.play();
        selectedRightCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/ImagesGUI/bigSize/greenCarRight.png")));
        rightCarSelection = "green";
        p2SelectedColour = true;
    }//GEN-LAST:event_greenCarRightIconMouseClicked

    private void purpleCarRightIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purpleCarRightIconMouseClicked
        buttonSelect.play();
        selectedRightCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/ImagesGUI/bigSize/purpleCarRight.png")));
        rightCarSelection = "purple";
        p2SelectedColour = true;
    }//GEN-LAST:event_purpleCarRightIconMouseClicked

    private void redCarRightIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redCarRightIconMouseClicked
        buttonSelect.play();
        selectedRightCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/ImagesGUI/bigSize/redCarRight.png")));
        rightCarSelection = "red";
        System.out.println(rightCarSelection);
        p2SelectedColour = true;
    }//GEN-LAST:event_redCarRightIconMouseClicked

    private void yellowCarRightIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yellowCarRightIconMouseClicked
        buttonSelect.play();
        selectedRightCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineshootout/ImagesGUI/bigSize/yellowCarRight.png")));
        rightCarSelection = "yellow";
        p2SelectedColour = true;
    }//GEN-LAST:event_yellowCarRightIconMouseClicked
/**If the user hasn't entered their name or entered a blank name it will be set to the default Player 1 or Player 2
 * 
 * @param evt button clicked event
 */
    private void playButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playButtonMouseClicked
        if (p1SelectedColour && p2SelectedColour) {
            if (p1SelectedName == false || p1TextField.getText().equals("")) {
                p1TextField.setText("Player 1");
            }
            if (p2SelectedName == false || p2TextField.getText().equals("")) {
                p2TextField.setText("Player 2");
            }
            gui.setP1NameField(p1TextField.getText());
            gui.setP2NameField(p2TextField.getText());
            buttonConfirm.play();
            game.goNextStage();
        }
        else {
            buttonError.setVolume(0.3);
            buttonError.play();
        }
    }//GEN-LAST:event_playButtonMouseClicked

    private void p1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1TextFieldActionPerformed
        
    }//GEN-LAST:event_p1TextFieldActionPerformed

    private void p1TextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1TextFieldMouseClicked
        p1TextField.setText("");
        p1TextField.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_p1TextFieldMouseClicked

    private void p2TextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2TextFieldMouseClicked
        p2TextField.setText("");
        p2TextField.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_p2TextFieldMouseClicked

    /**
     *
     * @return method to access the text input for player 1
     */
    public String getP1TextField() {
        return p1TextField.getText();
    }

    /**
     *
     * @return method to access the text input for player 1
     */
    public String getP2TextField() {
        return p2TextField.getText();
    }

    private void p1OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1OkButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1OkButtonActionPerformed

    private void p1OkButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1OkButtonMouseClicked
        buttonConfirm.play();
        p1NameField.setText(p1TextField.getText());
        p1TextField.setVisible(false);
        p1OkButton.setVisible(false);
        p1EditButton.setVisible(true);
        p1SelectedName = true;
    }//GEN-LAST:event_p1OkButtonMouseClicked

    private void p2OkButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2OkButtonMouseClicked
        buttonConfirm.play();
        p2NameField.setText(p2TextField.getText());
        p2TextField.setVisible(false);
        p2OkButton.setVisible(false);
        p2EditButton.setVisible(true);
        p2SelectedName = true;
    }//GEN-LAST:event_p2OkButtonMouseClicked

    private void p1EditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1EditButtonMouseClicked
        buttonSelect.play();
        p1TextField.setVisible(true);
        p1OkButton.setVisible(true);
        p1NameField.setText("");
        p1EditButton.setVisible(false);
    }//GEN-LAST:event_p1EditButtonMouseClicked

    private void p2EditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2EditButtonMouseClicked
        buttonSelect.play();
        p2TextField.setVisible(true);
        p2OkButton.setVisible(true);
        p2NameField.setText("");
        p2EditButton.setVisible(false);
    }//GEN-LAST:event_p2EditButtonMouseClicked

    private void p2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2TextFieldActionPerformed

    private void creditsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditsButtonMouseClicked
        buttonSelect.play();
        creditsDialogMenu.setResizable(false);
        creditsDialogMenu.setSize(300, 500);
        creditsDialogMenu.setAlwaysOnTop(true);
        creditsDialogMenu.setLocation(450, 100);
        creditsDialogMenu.setVisible(true);
        creditsAudio.setEditable(false);
        creditsImages.setEditable(false);
    }//GEN-LAST:event_creditsButtonMouseClicked

    private void creditsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditsButtonActionPerformed

    private void quitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitButtonMouseClicked
        buttonSelect.play();
        System.exit(0);
    }//GEN-LAST:event_quitButtonMouseClicked

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quitButtonActionPerformed

    private void closeCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeCreditsActionPerformed
        closeCredits.setRolloverEnabled(false);
    }//GEN-LAST:event_closeCreditsActionPerformed

    private void closeCreditsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeCreditsMouseClicked
        buttonSelect.play();
        closeCredits.setRolloverEnabled(false);
        creditsDialogMenu.setVisible(false);
    }//GEN-LAST:event_closeCreditsMouseClicked

    private void instructionsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instructionsButtonMouseClicked
        buttonSelect.play();
        instructionsDialogMenu.setResizable(false);
        instructionsDialogMenu.setSize(905, 475);
        instructionsDialogMenu.setAlwaysOnTop(true);
        instructionsDialogMenu.setLocation(150, 100);
        instructionsDialogMenu.setVisible(true);
    }//GEN-LAST:event_instructionsButtonMouseClicked

    private void instructionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructionsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instructionsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blueCarLeftIcon;
    private javax.swing.JLabel blueCarRightIcon;
    private javax.swing.JButton closeCredits;
    private javax.swing.JTextArea creditsAudio;
    private javax.swing.JButton creditsButton;
    private javax.swing.JDialog creditsDialogMenu;
    private javax.swing.JTextArea creditsImages;
    private javax.swing.JLabel gameNameField;
    private javax.swing.JLabel greenCarLeftIcon;
    private javax.swing.JLabel greenCarRightIcon;
    private javax.swing.JButton instructionsButton;
    private javax.swing.JDialog instructionsDialogMenu;
    private javax.swing.JLabel instructionsImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton p1EditButton;
    private javax.swing.JLabel p1NameField;
    private javax.swing.JButton p1OkButton;
    private javax.swing.JTextField p1TextField;
    private javax.swing.JButton p2EditButton;
    private javax.swing.JLabel p2NameField;
    private javax.swing.JButton p2OkButton;
    private javax.swing.JTextField p2TextField;
    private javax.swing.JButton playButton;
    private javax.swing.JLabel purpleCarLeftIcon;
    private javax.swing.JLabel purpleCarRightIcon;
    private javax.swing.JButton quitButton;
    private javax.swing.JLabel redCarLeftIcon;
    private javax.swing.JLabel redCarRightIcon;
    private javax.swing.JLabel selectedLeftCar;
    private javax.swing.JLabel selectedRightCar;
    private javax.swing.JLabel yellowCarLeftIcon;
    private javax.swing.JLabel yellowCarRightIcon;
    // End of variables declaration//GEN-END:variables
}
